Repository 24-2-CapstoneDesign/Back_Spring, pull requests merged in 2024-06, with the labels that each got.

#7 Feat/3 : BaseException, TimeConverter 구현
  bookspud/src/main/java/com/potato/bookspud/domain/auth/jwt/JwtAuthenticationFilter.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/controller/BookController.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/domain/Book.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/domain/MyBook.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/request/BookCreateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookCountResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookCreateResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookDetailResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BooksResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/RecentBookResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/RecentBooksResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/exception/.gitkeep
  bookspud/src/main/java/com/potato/bookspud/domain/book/exception/RecentBookException.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/repository/BookRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/repository/MyBookRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/service/BookService.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookmark/domain/BookMark.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/BookReport.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/BookReportQuestion.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/repository/BookReportQuestionRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/repository/BookReportRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/BaseException.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/ErrorCode.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/SuccessCode.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/TimeConverter.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/domain/QuestionGuide.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/domain/VocaGuide.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/repository/QuestionGuideRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/repository/VocaGuideRepository.java
Labels: ✨ feature

#8 Feat/4 Book 도메인 구현
  bookspud/src/main/java/com/potato/bookspud/domain/auth/annotation/AccessTokenUserArgumentResolver.java
  bookspud/src/main/java/com/potato/bookspud/domain/auth/service/KakaoSocialService.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/controller/BookController.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/domain/MyBook.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/request/BookCreateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookCountResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookCreateResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookDetailResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BooksResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/RecentBookResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/RecentBooksResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/exception/RecentBookException.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/repository/MyBookRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/service/BookService.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/SuccessCode.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/controller/GuideController.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/domain/QuestionGuide.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/domain/VocaGuide.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/dto/response/QuestionGuideResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/dto/response/QuestionGuidesResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/dto/response/VocaGuideResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/dto/response/VocaGuidesResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/repository/QuestionGuideRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/repository/VocaGuideRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/service/QuestionGuideService.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/service/VocaGuideService.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/repository/UserRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/service/UserService.java
  bookspud/src/main/resources/application-local.yml
Labels: ✨ feature

#10 Feat/5 Book 도메인 기능 수정
  bookspud/src/main/java/com/potato/bookspud/domain/book/controller/BookController.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/domain/Book.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/domain/MyBook.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/request/BookCreateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/request/BookUpdateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookCountResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookDetailResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/dto/response/BookResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/repository/BookRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/repository/MyBookRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/service/BookService.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/SuccessCode.java
Labels: ✨ feature

#11 setting/2 application.yml 정리
  bookspud/src/main/resources/application-local.yml
  bookspud/src/main/resources/application-prod.yml
Labels: ⚙ Setting

#16 Feat/#12 BookReport ChatGPT 관련 기능 구현
  bookspud/build.gradle
  bookspud/src/main/java/com/potato/bookspud/domain/auth/config/SecurityConfig.java
  bookspud/src/main/java/com/potato/bookspud/domain/auth/service/KakaoSocialService.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/controller/BookController.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/service/BookService.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookmark/repository/BookMarkRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookmark/service/BookMarkService.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/controller/BookReportController.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/BookReport.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/BookReportQuestion.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/request/ArgumentCreateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/request/ArgumentsRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/ArgumentCreateResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/ArgumentsResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/QuestionsResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/repository/BookReportRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/service/BookReportQuestionService.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/service/BookReportService.java
  bookspud/src/main/java/com/potato/bookspud/domain/chatgpt/config/ChatGPTConfig.java
  bookspud/src/main/java/com/potato/bookspud/domain/chatgpt/controller/ChatGPTController.java
  bookspud/src/main/java/com/potato/bookspud/domain/chatgpt/dto/request/ChatGPTRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/chatgpt/dto/request/Message.java
  bookspud/src/main/java/com/potato/bookspud/domain/chatgpt/dto/response/ChatGPTResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/chatgpt/service/ChatGPTService.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/SuccessCode.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/SwaggerConfig.java
  bookspud/src/main/resources/application-local.yml
  bookspud/src/main/resources/application-prod.yml
Labels: ✨ feature

#17 Feature/#14 User 도메인 관련 기능 구현
  bookspud/src/main/java/com/potato/bookspud/domain/auth/client/KakaoUserProfile.java
  bookspud/src/main/java/com/potato/bookspud/domain/auth/service/KakaoSocialService.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/SuccessCode.java
  bookspud/src/main/java/com/potato/bookspud/domain/s3/config/S3Config.java
  bookspud/src/main/java/com/potato/bookspud/domain/s3/service/S3Service.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/controller/UserController.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/domain/User.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/dto/request/NicknameRegisterRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/dto/request/PointUpdateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/dto/request/ProfileRegisterRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/dto/response/GetPointResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/dto/response/ProfileRegisterResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/user/service/UserService.java
  bookspud/src/main/resources/application-local.yml
Labels: ⚙ Setting, ✨ feature

#18 Feat/#16 BookReport 생성 기능 구현
  bookspud/src/main/java/com/potato/bookspud/domain/book/controller/BookController.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/domain/MyBook.java
  bookspud/src/main/java/com/potato/bookspud/domain/book/service/BookService.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/controller/BookReportController.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/BookReport.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/BookReportQuestion.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/Status.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/request/DraftCreateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/request/FinalCreateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/ArgumentCreateResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/DraftResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/repository/BookReportQuestionRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/service/BookReportService.java
  bookspud/src/main/java/com/potato/bookspud/domain/chatgpt/controller/ChatGPTController.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/SuccessCode.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/controller/GuideController.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/domain/VocaGuide.java
  bookspud/src/main/java/com/potato/bookspud/domain/guide/service/VocaGuideService.java
Labels: ✨ feature

#21 Feat/#15 BookReport schema 수정 사항 반영 및 추가 기능 구현
  bookspud/src/main/java/com/potato/bookspud/domain/auth/service/KakaoSocialService.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/controller/BookReportController.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/BookReport.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/domain/BookReportContent.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/request/FinalCreateRequest.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/BookReportDetailResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/BookReportResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/BookReportsResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/dto/response/DraftResponse.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/repository/BookReportContentRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/repository/BookReportRepository.java
  bookspud/src/main/java/com/potato/bookspud/domain/bookreport/service/BookReportService.java
  bookspud/src/main/java/com/potato/bookspud/domain/chatgpt/controller/ChatGPTController.java
  bookspud/src/main/java/com/potato/bookspud/domain/common/SuccessCode.java
  bookspud/src/main/resources/application-prod.yml
Labels: ✨ feature
